### ISSUE TITLE
Document hb-subset

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/oxidize#8]
https://github.com/harfbuzz/harfbuzz/blob/main/docs/repacker.md is lovely, write up how the rest of subsetting works with code refs

**Comment by behdad** [comment]
* serializer design: https://goo.gl/bHvnTn
* subsetter design: https://goo.gl/Qy3Eqc

**Comment by rsheeter** [comment]
Do you need/want to add anything to that or can I close this?

**Comment by rsheeter** [comment]
I tend to think it still makes sense to describe how it works akin to how repacker.md does?

**Comment by behdad** [comment]
I feel like that can be a task for Garret now.

**Comment by rsheeter** [comment]
🚌=>@garretrieger

**Comment by garretrieger** [comment]
I just added a short writeup of how the serializer works in hb here: https://github.com/harfbuzz/harfbuzz/blob/main/docs/serializer.md

**Comment by rsheeter** [comment]
I think we can call this complete, thank you. I'll add links to the root readme.
